services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: solestride
    ports:
      - "8000:8000"  # Map port 8000 on the host to port 8000 in the container
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres.railway.internal  # Use Railway's PostgreSQL host
      DB_PORT: 5432  # Use Railway's PostgreSQL port
      DB_DATABASE: railway  # Use Railway's PostgreSQL database
      DB_USERNAME: postgres  # Use Railway's PostgreSQL username
      DB_PASSWORD: VMadqmERQCmWJBalhXyPXFrKdkWjZKBm  # Use Railway's PostgreSQL password
    command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]

  db:
    # The `db` service is not needed for Railway because it provides its own database
    # Uncomment this section if you want to test locally using Docker
    image: postgres:15
    container_name: solestride-db
    environment:
      POSTGRES_DB: solestride
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data  # Persist database data in a Docker volume
    ports:
      - "5432:5432"  # Map port 5432 on the host to port 5432 in the container

volumes:
  db_data:  # Define the volume for database persistence
