services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: solestride
    ports:
      - "10000:10000"  # Map port 10000 for Render
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: dpg-ctf05mlds78s73dldq40-a  # Render database host
      DB_PORT: 5432
      DB_DATABASE: solestride
      DB_USERNAME: postgres
      DB_PASSWORD: secret  # Render database password
    command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=10000"]
